#### **Classical Computing with Matrices Exercises**

##### Crie a representação matricial de uma operação NOT, AND, OR, NAND, NOR.

In [ ]:
NOT = np.array([[0,1],[1,0]]); NOT

array([[0, 1],
       [1, 0]])

In [ ]:
NOT.dot(D0)

array([[0],
       [1]])

In [ ]:
NOT.dot(D1)

array([[1],
       [0]])

In [ ]:
AND = np.array([[1,1,1,0],[0,0,0,1]]); AND

array([[1, 1, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
AND.dot(np.kron(D0,D0))

array([[1],
       [0]])

In [ ]:
AND.dot(np.kron(D0,D1))

array([[1],
       [0]])

In [ ]:
AND.dot(np.kron(D1,D0))

array([[1],
       [0]])

In [ ]:
AND.dot(np.kron(D1,D1))

array([[0],
       [1]])

In [ ]:
OR = np.array([[1,0,0,0],[0,1,1,1]]); OR

array([[1, 0, 0, 0],
       [0, 1, 1, 1]])

In [ ]:
OR.dot(np.kron(D0,D0))

array([[1],
       [0]])

In [ ]:
OR.dot(np.kron(D0,D1))

array([[0],
       [1]])

In [ ]:
OR.dot(np.kron(D1,D0))

array([[0],
       [1]])

In [ ]:
OR.dot(np.kron(D1,D1))

array([[0],
       [1]])

In [ ]:
NAND = np.array([[0,0,0,1],[1,1,1,0]]); NAND

array([[0, 0, 0, 1],
       [1, 1, 1, 0]])

In [ ]:
NOT.dot(AND)

array([[0, 0, 0, 1],
       [1, 1, 1, 0]])

In [ ]:
NOR = np.array([[0,1,1,1],[1,0,0,0]]);NOR

array([[0, 1, 1, 1],
       [1, 0, 0, 0]])

##### Comprove por multiplicação matricial que NOR = NOT.OR e NAND = NOT.AND

In [ ]:
NOT.dot(OR)

array([[0, 1, 1, 1],
       [1, 0, 0, 0]])

In [ ]:
np.kron(NOT,AND)

array([[0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
OR.dot(np.kron(NOT,AND))

array([[0, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 1]])

In [ ]:
NOT.dot(AND).dot(np.kron(NOT,NOT))

array([[1, 0, 0, 0],
       [0, 1, 1, 1]])

In [ ]:
OR

array([[1, 0, 0, 0],
       [0, 1, 1, 1]])

In [ ]:
NOT.dot(OR).dot(np.kron(NOT,NOT))

array([[1, 1, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
AND

array([[1, 1, 1, 0],
       [0, 0, 0, 1]])

##### Calcule a matriz de transferência para um circuito somador com o carry out bit. X Y irá gerar Z e cOut. Z é X XOR Y e cOut é X AND Y

In [ ]:
import numpy as np
k = np.kron
XOR = np.array([[1,0,0,1],
                [0,1,1,0]])
AND = np.array(([1,1,1,0],
                [0,0,0,1]))
k(XOR,AND)

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
def criaCompat(nbits,nvezes):
  nlins = 2**(nbits*nvezes)
  ncols = 2**nbits
  compat = np.zeros(nlins*ncols).reshape(nlins,ncols)
  for i in range(ncols):
   formato = "0" + str(nbits) + "b"
   binario = format(i,formato)*nvezes
   decimal = int(binario,2)
   compat[decimal,i] = 1
  return(compat)

criaCompat(2,2)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [ ]:
k(XOR,AND).dot(criaCompat(2,2))

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

##### A partir de três entradas c, x, y crie a representação matricial de um somador. Os dígitos são x e y e c é o carry-in. A saida deverá ser z e c' onde z é a soma e c' o carry out

$ \begin{bmatrix}
c & x & y & z & c' \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 \\
0 & 1 & 1 & 0 & 1 \\
1 & 0 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 & 1 \\
1 & 1 & 0 & 0 & 1 \\
1 & 1 & 1 & 1 & 1
\end{bmatrix}  $

In [ ]:
import numpy as np
k = np.kron

def criaCompat(nbits,nvezes):
  nlins = 2**(nbits*nvezes)
  ncols = 2**nbits
  compat = np.zeros(nlins*ncols).reshape(nlins,ncols)
  for i in range(ncols):
   formato = "0" + str(nbits) + "b"
   binario = format(i,formato)*nvezes
   decimal = int(binario,2)
   compat[decimal,i] = 1
  return(compat)

criaCompat(2,2)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [ ]:
NOT = np.array([[0,1],
                [1,0]])

AND3 = np.array([[1,1,1,1,1,1,1,0],
                 [0,0,0,0,0,0,0,1]])

OR4 = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

I2 = np.array([[1,0],
               [0,1]])

t1z = k(NOT,k(NOT,I2))
t2z = k(NOT,k(I2,NOT))
t3z = k(I2,k(NOT,NOT))
t4z = k(I2,k(I2,I2))
ORz = k(AND3,k(AND3,k(AND3,AND3)))
ORz = OR4.dot(ORz).dot(k(t1z,k(t2z,k(t3z,t4z))))

t1c = k(NOT,k(I2,I2))
t2c = k(I2,k(NOT,I2))
t3c = k(I2,k(I2,NOT))
t4c = k(I2,k(I2,I2))
ORc = k(AND3,k(AND3,k(AND3,AND3)))
ORc = OR4.dot(ORc).dot(k(t1c,k(t2c,k(t3c,t4c))))

compat = criaCompat(3,8)
k(ORz,ORc).dot(compat)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

##### Prove através de matrizes que o TOFFOLI gate é sua própria inversa

In [ ]:
import numpy as np
TOFFOLI = np.array([[1,0,0,0,0,0,0,0],
                    [0,1,0,0,0,0,0,0],
                    [0,0,1,0,0,0,0,0],
                    [0,0,0,1,0,0,0,0],
                    [0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],
                    [0,0,0,0,0,0,0,1],
                    [0,0,0,0,0,0,1,0]])
TOFFOLI.dot(TOFFOLI)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

##### Criar uma matriz de transferência para um circuito que recebe três entradas X, Y e Z e gera uma saida com três estados X, Y e Z=1

In [ ]:
Z1 = np.array([[0,0,0,0,0,0,0,0],
               [0,1,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,1,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,1,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,1]])
Z1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

##### Criar uma matriz de transferência para um circuito que recebe duas entradas X, Y e gera três saidas X, Y e Z=1

In [ ]:
Z1I4 = np.array([[0,0,0,0],
                 [1,0,0,0],
                 [0,0,0,0],
                 [0,1,0,0],
                 [0,0,0,0],
                 [0,0,1,0],
                 [0,0,0,0],
                 [0,0,0,1]])
TOFFOLI.dot(ZpY).dot(TOFFOLI).dot(Z1I4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.]])

##### Criar uma matriz de transferência para um circuito que recebe três entradas X, Y, Z e cria uma saida igual a X, Z, Y (isto é, inverte duas das entradas)

In [ ]:
ZpY = np.zeros([8,8])
ZpY[0,0] = 1; ZpY[1,2] = 1; ZpY[2,1] = 1; ZpY[3,3] = 1
ZpY[4,4] = 1; ZpY[5,6] = 1; ZpY[6,5] = 1; ZpY[7,7] = 1
ZpY

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

##### Criar uma matriz de transferência de um circuito que recebe três entradas X, Y, Z e gera uma saida igual a Z. (o digito menos significativo)

In [ ]:
Zfim = np.array([[1,0,1,0,1,0,1,0],
                 [0,1,0,1,0,1,0,1]])

##### Mostrar que circuito formado pela sequência abaixo gera na prática a operação lógica X OR Y = Z:
a) Duas entradas X, Y
b) Um gate que recebe X, Y e gera X, Y e Z=1
c) Um gate Toffoli (X e Y controle, Z target)
d) Um gate que recebe X, Y, Z e gera X, Z, Y
e) Um gate Toffoli (idem anterior)
f) Um gate que recebe X, Y e Z e gera uma saida igual a Z


In [ ]:
Zfim.dot(TOFFOLI).dot(ZpY).dot(TOFFOLI).dot(Z1I4)

array([[1., 0., 0., 0.],
       [0., 1., 1., 1.]])

##### Mostrar que um gate Fredkin é sua própria inversa. Um gate Fredkin tem três entradas X, Y, Z e três saidas X', Y' e Z'. X'= X sempre. Quando X=0, Y'=Y e Z'=Z. Quando X=1, Y e Z tem seus valores invertidos, isto é Y'=Z e Z'=Y

In [ ]:
import numpy as np
fred = np.identity(8)
fred[5,5] = 0; fred[5,6] = 1
fred[6,5] = 1; fred[6,6] = 0
fred

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
fred.dot(fred)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

##### Crie uma matriz de transferência para um gate de duas entradas XZ e três saidas XYZ, onde Y=0

In [ ]:
import numpy as np
Fy0 = np.zeros([8,4])
Fy0[0,0] = 1; Fy0[1,1] = 1; Fy0[4,2] = 1; Fy0[5,3] = 1
Fy0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### Crie uma matriz de transferência a qual recebe três entradas XYZ e devolve uma saida igual a Y (o segundo dígito mais significativo)

In [ ]:
xYz = np.array([[1,1,0,0,1,1,0,0],
                [0,0,1,1,0,0,1,1]])

##### Mostre que as três matrizes anteriores fazem com que o Fredkin gate gere a operação Y' = X AND Z

In [ ]:
xYz.dot(fred).dot(Fy0)

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.]])