FAST FOURIER TRANSFORM

Para lembrar:

Suponha $n = 4$. Vamos transformar a multiplicação de uma matriz 4x4 por um vetor 4x1 ($n^2 = 16$ produtos) em ($n \log_2{n} = 8$ produtos)

$$W = e^{\frac{2 \pi j}{n}}$$

$$W_4 = e^{\frac{2 \pi j}{4}} = j$$

$$W_2 = e^{\frac{2 \pi j}{2}} = -1$$

A DFT para uma sequência de 4 pontos seria:
$$
\begin{array}{ccc}
\begin{bmatrix}
F_0 \\
F_1 \\
F_2 \\
F_3
\end{bmatrix}
&
=
&
\begin{bmatrix}
1 & 1       & 1 & 1 \\
1 & W_4     & W_4^{2} & W_4^{3} \\
1 & W_4^{2} & W_4^{4} & W_4^{6} \\
1 & W_4^{3} & W_4^{6} & W_4^{9}
\end{bmatrix}
&
.
&
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3
\end{bmatrix}
\end{array}
$$

$$
\begin{array}{ccc}
\begin{bmatrix}
F_0 \\
F_1 \\
F_2 \\
F_3
\end{bmatrix}
&
=
&
\begin{bmatrix}
1 & 1     & 1     & 1 \\
1 & j     & j^{2} & j^{3} \\
1 & j^{2} & j^{4} & j^{6} \\
1 & j^{3} & j^{6} & j^{9}
\end{bmatrix}
&
.
&
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3
\end{bmatrix}
\end{array}
$$

$$
\begin{array}{ccc}
\begin{bmatrix}
F_0 \\
F_1 \\
F_2 \\
F_3
\end{bmatrix}
&
=
&
\begin{bmatrix}
1 & 1  & 1     & 1 \\
1 & j  & -1 & -j \\
1 & -1 & 1 & 1 \\
1 & -j & -1 & -j
\end{bmatrix}
&
.
&
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3
\end{bmatrix}
\end{array}
$$

A multiplicação em 8 passos seria feita de acordo com a sequência abaixo:

$$
\begin{array}{ccc}
\begin{bmatrix}
F_0 \\
F_1 \\
F_2 \\
F_3
\end{bmatrix}
&
=
&
\begin{bmatrix}
1 & 0  & 1 & 0 \\
0 & 1  & 0 & j \\
1 & 0 & -1 & 0 \\
0 & 1 & 0 & -j
\end{bmatrix}
&
.
&
\begin{bmatrix}
1 & 1  & 0 & 0 \\
1 & -1  & 0 & 0 \\
0 & 0 & 1 & 1 \\
0 & 0 & 1 & -1
\end{bmatrix}
&
.
&
\begin{bmatrix}
1 & 0  & 0 & 0 \\
0 & 0  & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
&
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3
\end{bmatrix}
\end{array}
$$

$$
\begin{array}{ccc}
\begin{bmatrix}
F_0 \\
F_1 \\
F_2 \\
F_3
\end{bmatrix}
&
=
&
\begin{bmatrix}
I_2 & D_{4_2} \\
I_2 & -D_{4_2} \\
\end{bmatrix}
&
.
&
\begin{bmatrix}
DFT_2 & Z_2 \\
Z_2   & DFT_2 \\
\end{bmatrix}
&
.
&
\begin{bmatrix}
P_{even}  \\
P_{odd}  \\
\end{bmatrix}
&
.
&
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3
\end{bmatrix}
\end{array}
$$

In [ ]:
def chop(x, tol=1.e-14):
  r = np.real(x)
  if abs(r)<tol:
    r = 0

  i = np.imag(x)
  if abs(i)<tol:
    i = 0

  if i == 0:
    n = r
  elif r == 0:
    n = i*1j
  else:
    n = r + i*1j
  return(n)

import numpy as np
a = 1e-16 + 1e-16*1j
b = 1e-16 + 1j
c = 1 + 1e-16*1j
chop(a), chop(b), chop(c)

(0, 1j, 1.0)

In [ ]:
n = 4
w4 = np.exp(2*np.pi*1j/n)
w4 = chop(w4)
w4

1j

In [ ]:
F4 = np.zeros([4,4], dtype=complex)
for i in range(4):
    for j in range(4):
        F4[i,j] = w4**(i*j)
F4

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j]])

In [ ]:
I2 = np.array([[1,0],[0,1]]); I2

array([[1, 0],
       [0, 1]])

In [ ]:
D2_4 = np.zeros([2,2], dtype=complex)
for i in range(2):
  D2_4[i,i] = w4**(i)
D2_4

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [ ]:
M1 = np.concatenate([I2,D2_4],axis=1)
M2 = np.concatenate([I2,-D2_4],axis=1)
M3 = np.concatenate([M1,M2],axis=0); M3

array([[ 1.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+1.j],
       [ 1.+0.j,  0.+0.j, -1.-0.j, -0.-0.j],
       [ 0.+0.j,  1.+0.j, -0.-0.j, -0.-1.j]])

In [ ]:
n = 2
w2 = np.exp(2*np.pi*1j/n)
w2 = chop(w2)
w2

-1.0

In [ ]:
F2 = np.zeros([2,2], dtype=complex)
for i in range(2):
    for j in range(2):
        F2[i,j] = w2**(i*j)
F2

array([[ 1.+0.j,  1.+0.j],
       [ 1.+0.j, -1.+0.j]])

In [ ]:
Z2 = np.zeros([2,2], dtype=complex)
Z2

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [ ]:
K1 = np.concatenate([F2,Z2],axis=1)
K2 = np.concatenate([Z2,F2],axis=1)
K3 = np.concatenate([K1,K2],axis=0); K3

array([[ 1.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j, -1.+0.j]])

In [ ]:
P4 = np.array([[1,0,0,0],
               [0,0,1,0],
               [0,1,0,0],
               [0,0,0,1]])
P4

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [ ]:
M3.dot(K3).dot(P4)

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j,  0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j]])

In [ ]:
F4

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j]])

In [ ]:
np.all(F4 == M3.dot(K3).dot(P4))

True